// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pitmessage.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EnumPitType int32

const (
	EnumPitType_UNKNOWN          EnumPitType = 0
	EnumPitType_SYSTEM           EnumPitType = 1
	EnumPitType_SYSTEM_CPU       EnumPitType = 2
	EnumPitType_SYSTEM_MEMORY    EnumPitType = 3
	EnumPitType_PROC             EnumPitType = 10
	EnumPitType_PROC_CPU_PERCENT EnumPitType = 11
	EnumPitType_PROC_MEM_INFO    EnumPitType = 12
	EnumPitType_PROC_MEM_PERCENT EnumPitType = 13
	EnumPitType_QUERY_INFO       EnumPitType = 14
	EnumPitType_EXEC_INFO        EnumPitType = 15
)

var EnumPitType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SYSTEM",
	2:  "SYSTEM_CPU",
	3:  "SYSTEM_MEMORY",
	10: "PROC",
	11: "PROC_CPU_PERCENT",
	12: "PROC_MEM_INFO",
	13: "PROC_MEM_PERCENT",
	14: "QUERY_INFO",
	15: "EXEC_INFO",
}
var EnumPitType_value = map[string]int32{
	"UNKNOWN":          0,
	"SYSTEM":           1,
	"SYSTEM_CPU":       2,
	"SYSTEM_MEMORY":    3,
	"PROC":             10,
	"PROC_CPU_PERCENT": 11,
	"PROC_MEM_INFO":    12,
	"PROC_MEM_PERCENT": 13,
	"QUERY_INFO":       14,
	"EXEC_INFO":        15,
}

func (x EnumPitType) String() string {
	return proto.EnumName(EnumPitType_name, int32(x))
}
func (EnumPitType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type PitMessage struct {
	PitType EnumPitType `protobuf:"varint,1,opt,name=pit_type,json=pitType,enum=protos.EnumPitType" json:"pit_type,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*PitMessage_SystemCpu
	//	*PitMessage_ProcCpuPercent
	//	*PitMessage_ProcMemInfo
	//	*PitMessage_ProcMemPercent
	//	*PitMessage_QueryInfo
	//	*PitMessage_ExecInfo
	Message isPitMessage_Message `protobuf_oneof:"message"`
}

func (m *PitMessage) Reset()                    { *m = PitMessage{} }
func (m *PitMessage) String() string            { return proto.CompactTextString(m) }
func (*PitMessage) ProtoMessage()               {}
func (*PitMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isPitMessage_Message interface {
	isPitMessage_Message()
}

type PitMessage_SystemCpu struct {
	SystemCpu *SystemCpu `protobuf:"bytes,2,opt,name=system_cpu,json=systemCpu,oneof"`
}
type PitMessage_ProcCpuPercent struct {
	ProcCpuPercent *ProcCpuPercent `protobuf:"bytes,3,opt,name=proc_cpu_percent,json=procCpuPercent,oneof"`
}
type PitMessage_ProcMemInfo struct {
	ProcMemInfo *ProcMemInfo `protobuf:"bytes,4,opt,name=proc_mem_info,json=procMemInfo,oneof"`
}
type PitMessage_ProcMemPercent struct {
	ProcMemPercent *ProcMemPercent `protobuf:"bytes,5,opt,name=proc_mem_percent,json=procMemPercent,oneof"`
}
type PitMessage_QueryInfo struct {
	QueryInfo *QueryInfo `protobuf:"bytes,6,opt,name=query_info,json=queryInfo,oneof"`
}
type PitMessage_ExecInfo struct {
	ExecInfo *ExecInfo `protobuf:"bytes,7,opt,name=exec_info,json=execInfo,oneof"`
}

func (*PitMessage_SystemCpu) isPitMessage_Message()      {}
func (*PitMessage_ProcCpuPercent) isPitMessage_Message() {}
func (*PitMessage_ProcMemInfo) isPitMessage_Message()    {}
func (*PitMessage_ProcMemPercent) isPitMessage_Message() {}
func (*PitMessage_QueryInfo) isPitMessage_Message()      {}
func (*PitMessage_ExecInfo) isPitMessage_Message()       {}

func (m *PitMessage) GetMessage() isPitMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PitMessage) GetPitType() EnumPitType {
	if m != nil {
		return m.PitType
	}
	return EnumPitType_UNKNOWN
}

func (m *PitMessage) GetSystemCpu() *SystemCpu {
	if x, ok := m.GetMessage().(*PitMessage_SystemCpu); ok {
		return x.SystemCpu
	}
	return nil
}

func (m *PitMessage) GetProcCpuPercent() *ProcCpuPercent {
	if x, ok := m.GetMessage().(*PitMessage_ProcCpuPercent); ok {
		return x.ProcCpuPercent
	}
	return nil
}

func (m *PitMessage) GetProcMemInfo() *ProcMemInfo {
	if x, ok := m.GetMessage().(*PitMessage_ProcMemInfo); ok {
		return x.ProcMemInfo
	}
	return nil
}

func (m *PitMessage) GetProcMemPercent() *ProcMemPercent {
	if x, ok := m.GetMessage().(*PitMessage_ProcMemPercent); ok {
		return x.ProcMemPercent
	}
	return nil
}

func (m *PitMessage) GetQueryInfo() *QueryInfo {
	if x, ok := m.GetMessage().(*PitMessage_QueryInfo); ok {
		return x.QueryInfo
	}
	return nil
}

func (m *PitMessage) GetExecInfo() *ExecInfo {
	if x, ok := m.GetMessage().(*PitMessage_ExecInfo); ok {
		return x.ExecInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PitMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PitMessage_OneofMarshaler, _PitMessage_OneofUnmarshaler, _PitMessage_OneofSizer, []interface{}{
		(*PitMessage_SystemCpu)(nil),
		(*PitMessage_ProcCpuPercent)(nil),
		(*PitMessage_ProcMemInfo)(nil),
		(*PitMessage_ProcMemPercent)(nil),
		(*PitMessage_QueryInfo)(nil),
		(*PitMessage_ExecInfo)(nil),
	}
}

func _PitMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PitMessage)
	// message
	switch x := m.Message.(type) {
	case *PitMessage_SystemCpu:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SystemCpu); err != nil {
			return err
		}
	case *PitMessage_ProcCpuPercent:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProcCpuPercent); err != nil {
			return err
		}
	case *PitMessage_ProcMemInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProcMemInfo); err != nil {
			return err
		}
	case *PitMessage_ProcMemPercent:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProcMemPercent); err != nil {
			return err
		}
	case *PitMessage_QueryInfo:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.QueryInfo); err != nil {
			return err
		}
	case *PitMessage_ExecInfo:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExecInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PitMessage.Message has unexpected type %T", x)
	}
	return nil
}

func _PitMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PitMessage)
	switch tag {
	case 2: // message.system_cpu
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SystemCpu)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_SystemCpu{msg}
		return true, err
	case 3: // message.proc_cpu_percent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProcCpuPercent)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_ProcCpuPercent{msg}
		return true, err
	case 4: // message.proc_mem_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProcMemInfo)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_ProcMemInfo{msg}
		return true, err
	case 5: // message.proc_mem_percent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProcMemPercent)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_ProcMemPercent{msg}
		return true, err
	case 6: // message.query_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(QueryInfo)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_QueryInfo{msg}
		return true, err
	case 7: // message.exec_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExecInfo)
		err := b.DecodeMessage(msg)
		m.Message = &PitMessage_ExecInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PitMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PitMessage)
	// message
	switch x := m.Message.(type) {
	case *PitMessage_SystemCpu:
		s := proto.Size(x.SystemCpu)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PitMessage_ProcCpuPercent:
		s := proto.Size(x.ProcCpuPercent)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PitMessage_ProcMemInfo:
		s := proto.Size(x.ProcMemInfo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PitMessage_ProcMemPercent:
		s := proto.Size(x.ProcMemPercent)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PitMessage_QueryInfo:
		s := proto.Size(x.QueryInfo)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PitMessage_ExecInfo:
		s := proto.Size(x.ExecInfo)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PitMessageBox struct {
	Messages []*PitMessage `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
}

func (m *PitMessageBox) Reset()                    { *m = PitMessageBox{} }
func (m *PitMessageBox) String() string            { return proto.CompactTextString(m) }
func (*PitMessageBox) ProtoMessage()               {}
func (*PitMessageBox) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PitMessageBox) GetMessages() []*PitMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*PitMessage)(nil), "protos.PitMessage")
	proto.RegisterType((*PitMessageBox)(nil), "protos.PitMessageBox")
	proto.RegisterEnum("protos.EnumPitType", EnumPitType_name, EnumPitType_value)
}

func init() { proto.RegisterFile("pitmessage.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x41, 0x6f, 0x9b, 0x30,
	0x14, 0x0e, 0x4d, 0x97, 0x84, 0x47, 0xc9, 0x5c, 0x77, 0x9a, 0x50, 0x4f, 0x51, 0x4f, 0xd1, 0x0e,
	0x99, 0x94, 0x9d, 0x76, 0x9a, 0x14, 0xe4, 0x29, 0xd5, 0x64, 0xa0, 0x4e, 0xa2, 0x2d, 0x27, 0xb4,
	0x21, 0x77, 0xe2, 0x00, 0xb8, 0xd8, 0x48, 0xe1, 0xf7, 0xec, 0x17, 0xec, 0x1f, 0x4e, 0xb6, 0x81,
	0xb4, 0xeb, 0x89, 0xf7, 0x7d, 0xef, 0xfb, 0xde, 0x87, 0xfd, 0x0c, 0x48, 0xe4, 0xaa, 0xe0, 0x52,
	0xfe, 0xfc, 0xcd, 0x57, 0xa2, 0xae, 0x54, 0x85, 0x27, 0xe6, 0x23, 0x6f, 0xaf, 0x64, 0x2b, 0x15,
	0x2f, 0x2c, 0x7b, 0xeb, 0x3d, 0x35, 0xbc, 0x6e, 0x2d, 0xb8, 0xfb, 0x33, 0x06, 0x48, 0x72, 0x45,
	0xad, 0x0f, 0xaf, 0x60, 0x26, 0x72, 0x95, 0xaa, 0x56, 0xf0, 0xc0, 0x59, 0x38, 0xcb, 0xf9, 0xfa,
	0xc6, 0x0a, 0xe5, 0x8a, 0x94, 0x4d, 0x91, 0xe4, 0x6a, 0xdf, 0x0a, 0xce, 0xa6, 0xc2, 0x16, 0x78,
	0x0d, 0x60, 0x67, 0xa7, 0x99, 0x68, 0x82, 0x8b, 0x85, 0xb3, 0xf4, 0xd6, 0xd7, 0xbd, 0x63, 0x67,
	0x3a, 0xa1, 0x68, 0xb6, 0x23, 0xe6, 0xca, 0x1e, 0xe0, 0x0d, 0x20, 0x51, 0x57, 0x99, 0x76, 0xa4,
	0x82, 0xd7, 0x19, 0x2f, 0x55, 0x30, 0x36, 0xce, 0xf7, 0xbd, 0x33, 0xa9, 0xab, 0x2c, 0x14, 0x4d,
	0x62, 0xbb, 0xdb, 0x11, 0x9b, 0x8b, 0x17, 0x0c, 0xfe, 0x0c, 0xbe, 0x99, 0x51, 0xf0, 0x22, 0xcd,
	0xcb, 0xc7, 0x2a, 0xb8, 0x34, 0x03, 0x6e, 0x9e, 0x0f, 0xa0, 0xbc, 0xb8, 0x2f, 0x1f, 0xab, 0xed,
	0x88, 0x79, 0xe2, 0x0c, 0x87, 0x78, 0x6d, 0xed, 0xe3, 0xdf, 0xbc, 0x8e, 0xa7, 0xbc, 0xf8, 0x2f,
	0xfe, 0xcc, 0xe8, 0x63, 0x9b, 0x4b, 0xb4, 0xd9, 0x93, 0x97, 0xc7, 0x7e, 0xd0, 0x9d, 0x2e, 0xd9,
	0x7d, 0xea, 0x01, 0xfe, 0x08, 0x2e, 0x3f, 0xf1, 0xcc, 0x5a, 0xa6, 0xc6, 0x82, 0x86, 0xbb, 0x3d,
	0xf1, 0xac, 0x73, 0xcc, 0x78, 0x57, 0x6f, 0x5c, 0x98, 0x76, 0xeb, 0xbc, 0xfb, 0x02, 0xfe, 0x79,
	0x49, 0x9b, 0xea, 0xa4, 0xf7, 0xd4, 0xf5, 0x64, 0xe0, 0x2c, 0xc6, 0x4b, 0x6f, 0x8d, 0x87, 0x9f,
	0x1f, 0x84, 0x6c, 0xd0, 0x7c, 0xf8, 0xeb, 0x80, 0xf7, 0x6c, 0x81, 0xd8, 0x83, 0xe9, 0x21, 0xfa,
	0x16, 0xc5, 0xdf, 0x23, 0x34, 0xc2, 0x00, 0x93, 0xdd, 0x71, 0xb7, 0x27, 0x14, 0x39, 0x78, 0x0e,
	0x60, 0xeb, 0x34, 0x4c, 0x0e, 0xe8, 0x02, 0x5f, 0x83, 0xdf, 0x61, 0x4a, 0x68, 0xcc, 0x8e, 0x68,
	0x8c, 0x67, 0x70, 0x99, 0xb0, 0x38, 0x44, 0x80, 0xdf, 0x01, 0xd2, 0x95, 0x96, 0xa6, 0x09, 0x61,
	0x21, 0x89, 0xf6, 0xc8, 0xd3, 0x16, 0xc3, 0x52, 0x42, 0xd3, 0xfb, 0xe8, 0x6b, 0x8c, 0xae, 0x06,
	0xa1, 0xa6, 0x7a, 0xa1, 0xaf, 0xb3, 0x1e, 0x0e, 0x84, 0x1d, 0xad, 0x6a, 0x8e, 0x7d, 0x70, 0xc9,
	0x0f, 0x12, 0x5a, 0xf8, 0xf6, 0x97, 0x7d, 0xbd, 0x9f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x81, 0xd8, 0x24, 0xd8, 0x02, 0x00, 0x00,
}
