// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EnumQueryStatus int32

const (
	EnumQueryStatus_QUERY_SILENT    EnumQueryStatus = 0
	EnumQueryStatus_QUERY_SUBMIT    EnumQueryStatus = 1
	EnumQueryStatus_QUERY_START     EnumQueryStatus = 2
	EnumQueryStatus_QUERY_DONE      EnumQueryStatus = 3
	EnumQueryStatus_QUERY_ERROR     EnumQueryStatus = 4
	EnumQueryStatus_QUERY_CANCELING EnumQueryStatus = 5
)

var EnumQueryStatus_name = map[int32]string{
	0: "QUERY_SILENT",
	1: "QUERY_SUBMIT",
	2: "QUERY_START",
	3: "QUERY_DONE",
	4: "QUERY_ERROR",
	5: "QUERY_CANCELING",
}
var EnumQueryStatus_value = map[string]int32{
	"QUERY_SILENT":    0,
	"QUERY_SUBMIT":    1,
	"QUERY_START":     2,
	"QUERY_DONE":      3,
	"QUERY_ERROR":     4,
	"QUERY_CANCELING": 5,
}

func (x EnumQueryStatus) String() string {
	return proto.EnumName(EnumQueryStatus_name, int32(x))
}
func (EnumQueryStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type EnumNodeStatus int32

const (
	EnumNodeStatus_NODE_INIT  EnumNodeStatus = 0
	EnumNodeStatus_NODE_START EnumNodeStatus = 1
	EnumNodeStatus_NODE_DONE  EnumNodeStatus = 2
)

var EnumNodeStatus_name = map[int32]string{
	0: "NODE_INIT",
	1: "NODE_START",
	2: "NODE_DONE",
}
var EnumNodeStatus_value = map[string]int32{
	"NODE_INIT":  0,
	"NODE_START": 1,
	"NODE_DONE":  2,
}

func (x EnumNodeStatus) String() string {
	return proto.EnumName(EnumNodeStatus_name, int32(x))
}
func (EnumNodeStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type DistributedNodeKey struct {
	SegId  int32 `protobuf:"varint,1,opt,name=seg_id,json=segId" json:"seg_id,omitempty"`
	ProcId int32 `protobuf:"varint,2,opt,name=proc_id,json=procId" json:"proc_id,omitempty"`
	NodeId int32 `protobuf:"varint,3,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *DistributedNodeKey) Reset()                    { *m = DistributedNodeKey{} }
func (m *DistributedNodeKey) String() string            { return proto.CompactTextString(m) }
func (*DistributedNodeKey) ProtoMessage()               {}
func (*DistributedNodeKey) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *DistributedNodeKey) GetSegId() int32 {
	if m != nil {
		return m.SegId
	}
	return 0
}

func (m *DistributedNodeKey) GetProcId() int32 {
	if m != nil {
		return m.ProcId
	}
	return 0
}

func (m *DistributedNodeKey) GetNodeId() int32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type PlumInstrument struct {
	Key           *DistributedNodeKey `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Running       bool                `protobuf:"varint,2,opt,name=running" json:"running,omitempty"`
	FirstTuple    float64             `protobuf:"fixed64,3,opt,name=first_tuple,json=firstTuple" json:"first_tuple,omitempty"`
	TupleCount    float64             `protobuf:"fixed64,4,opt,name=tuple_count,json=tupleCount" json:"tuple_count,omitempty"`
	StartUp       float64             `protobuf:"fixed64,5,opt,name=start_up,json=startUp" json:"start_up,omitempty"`
	Total         float64             `protobuf:"fixed64,6,opt,name=total" json:"total,omitempty"`
	Ntuples       float64             `protobuf:"fixed64,7,opt,name=ntuples" json:"ntuples,omitempty"`
	Nloops        float64             `protobuf:"fixed64,8,opt,name=nloops" json:"nloops,omitempty"`
	ExecMemUsed   float64             `protobuf:"fixed64,9,opt,name=exec_mem_used,json=execMemUsed" json:"exec_mem_used,omitempty"`
	WorkMemUsed   float64             `protobuf:"fixed64,10,opt,name=work_mem_used,json=workMemUsed" json:"work_mem_used,omitempty"`
	WorkMemWanted float64             `protobuf:"fixed64,11,opt,name=work_mem_wanted,json=workMemWanted" json:"work_mem_wanted,omitempty"`
}

func (m *PlumInstrument) Reset()                    { *m = PlumInstrument{} }
func (m *PlumInstrument) String() string            { return proto.CompactTextString(m) }
func (*PlumInstrument) ProtoMessage()               {}
func (*PlumInstrument) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *PlumInstrument) GetKey() *DistributedNodeKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PlumInstrument) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *PlumInstrument) GetFirstTuple() float64 {
	if m != nil {
		return m.FirstTuple
	}
	return 0
}

func (m *PlumInstrument) GetTupleCount() float64 {
	if m != nil {
		return m.TupleCount
	}
	return 0
}

func (m *PlumInstrument) GetStartUp() float64 {
	if m != nil {
		return m.StartUp
	}
	return 0
}

func (m *PlumInstrument) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PlumInstrument) GetNtuples() float64 {
	if m != nil {
		return m.Ntuples
	}
	return 0
}

func (m *PlumInstrument) GetNloops() float64 {
	if m != nil {
		return m.Nloops
	}
	return 0
}

func (m *PlumInstrument) GetExecMemUsed() float64 {
	if m != nil {
		return m.ExecMemUsed
	}
	return 0
}

func (m *PlumInstrument) GetWorkMemUsed() float64 {
	if m != nil {
		return m.WorkMemUsed
	}
	return 0
}

func (m *PlumInstrument) GetWorkMemWanted() float64 {
	if m != nil {
		return m.WorkMemWanted
	}
	return 0
}

type QueryInfo struct {
	QueryId    string                     `protobuf:"bytes,1,opt,name=query_id,json=queryId" json:"query_id,omitempty"`
	Database   string                     `protobuf:"bytes,2,opt,name=database" json:"database,omitempty"`
	User       string                     `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	SubmitTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty"`
	StartTime  *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	FinishTime *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	Status     EnumQueryStatus            `protobuf:"varint,7,opt,name=status,enum=protos.EnumQueryStatus" json:"status,omitempty"`
}

func (m *QueryInfo) Reset()                    { *m = QueryInfo{} }
func (m *QueryInfo) String() string            { return proto.CompactTextString(m) }
func (*QueryInfo) ProtoMessage()               {}
func (*QueryInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *QueryInfo) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *QueryInfo) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *QueryInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *QueryInfo) GetSubmitTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

func (m *QueryInfo) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *QueryInfo) GetFinishTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *QueryInfo) GetStatus() EnumQueryStatus {
	if m != nil {
		return m.Status
	}
	return EnumQueryStatus_QUERY_SILENT
}

type ExecInfo struct {
	QueryId     string              `protobuf:"bytes,1,opt,name=query_id,json=queryId" json:"query_id,omitempty"`
	NodeKey     *DistributedNodeKey `protobuf:"bytes,2,opt,name=node_key,json=nodeKey" json:"node_key,omitempty"`
	Status      EnumNodeStatus      `protobuf:"varint,3,opt,name=status,enum=protos.EnumNodeStatus" json:"status,omitempty"`
	StartupCost float64             `protobuf:"fixed64,4,opt,name=startup_cost,json=startupCost" json:"startup_cost,omitempty"`
	TotalCost   float64             `protobuf:"fixed64,5,opt,name=total_cost,json=totalCost" json:"total_cost,omitempty"`
	PlanRows    float64             `protobuf:"fixed64,6,opt,name=plan_rows,json=planRows" json:"plan_rows,omitempty"`
	NodeType    int32               `protobuf:"varint,7,opt,name=node_type,json=nodeType" json:"node_type,omitempty"`
}

func (m *ExecInfo) Reset()                    { *m = ExecInfo{} }
func (m *ExecInfo) String() string            { return proto.CompactTextString(m) }
func (*ExecInfo) ProtoMessage()               {}
func (*ExecInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ExecInfo) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *ExecInfo) GetNodeKey() *DistributedNodeKey {
	if m != nil {
		return m.NodeKey
	}
	return nil
}

func (m *ExecInfo) GetStatus() EnumNodeStatus {
	if m != nil {
		return m.Status
	}
	return EnumNodeStatus_NODE_INIT
}

func (m *ExecInfo) GetStartupCost() float64 {
	if m != nil {
		return m.StartupCost
	}
	return 0
}

func (m *ExecInfo) GetTotalCost() float64 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *ExecInfo) GetPlanRows() float64 {
	if m != nil {
		return m.PlanRows
	}
	return 0
}

func (m *ExecInfo) GetNodeType() int32 {
	if m != nil {
		return m.NodeType
	}
	return 0
}

func init() {
	proto.RegisterType((*DistributedNodeKey)(nil), "protos.DistributedNodeKey")
	proto.RegisterType((*PlumInstrument)(nil), "protos.PlumInstrument")
	proto.RegisterType((*QueryInfo)(nil), "protos.QueryInfo")
	proto.RegisterType((*ExecInfo)(nil), "protos.ExecInfo")
	proto.RegisterEnum("protos.EnumQueryStatus", EnumQueryStatus_name, EnumQueryStatus_value)
	proto.RegisterEnum("protos.EnumNodeStatus", EnumNodeStatus_name, EnumNodeStatus_value)
}

func init() { proto.RegisterFile("query.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x35, 0x49, 0xf3, 0xb1, 0x77, 0xdb, 0x24, 0x8c, 0xda, 0xae, 0x15, 0xa9, 0xe6, 0x41, 0xa4,
	0x48, 0x0a, 0x15, 0x1f, 0xa4, 0x20, 0xd4, 0x74, 0x91, 0xc5, 0x36, 0xb5, 0xd3, 0x04, 0xf1, 0x41,
	0x96, 0x4d, 0x76, 0x1a, 0x97, 0x66, 0x67, 0xd6, 0x9d, 0x19, 0xd2, 0x80, 0x3f, 0xc0, 0x1f, 0xe5,
	0x5f, 0xf2, 0x3f, 0xc8, 0xdc, 0xd9, 0x4d, 0x5b, 0x7d, 0xc8, 0x53, 0x72, 0xcf, 0x39, 0x37, 0xf7,
	0xce, 0x99, 0x33, 0x01, 0xf7, 0x87, 0x66, 0xf9, 0xb2, 0x9f, 0xe5, 0x42, 0x09, 0xd2, 0xc0, 0x0f,
	0xb9, 0xbb, 0x37, 0x13, 0x62, 0x36, 0x67, 0x07, 0x58, 0x4e, 0xf4, 0xd5, 0x81, 0x4a, 0x52, 0x26,
	0x55, 0x94, 0x66, 0x56, 0xd8, 0xfb, 0x06, 0xe4, 0x24, 0x91, 0x2a, 0x4f, 0x26, 0x5a, 0xb1, 0x78,
	0x28, 0x62, 0xf6, 0x89, 0x2d, 0xc9, 0x63, 0x68, 0x48, 0x36, 0x0b, 0x93, 0xd8, 0xab, 0x3c, 0xaf,
	0xbc, 0xaa, 0xd3, 0xba, 0x64, 0xb3, 0x20, 0x26, 0x3b, 0xd0, 0xcc, 0x72, 0x31, 0x35, 0x78, 0x15,
	0x71, 0x33, 0x66, 0x6a, 0x09, 0x2e, 0x62, 0x66, 0x88, 0x9a, 0x25, 0x4c, 0x19, 0xc4, 0xbd, 0x3f,
	0x55, 0x68, 0x7f, 0x9e, 0xeb, 0x34, 0xe0, 0x52, 0xe5, 0x3a, 0x65, 0x5c, 0x91, 0xd7, 0x50, 0xbb,
	0x66, 0x4b, 0xfc, 0x61, 0xf7, 0x70, 0xd7, 0xae, 0x21, 0xfb, 0xff, 0x2f, 0x41, 0x8d, 0x8c, 0x78,
	0xd0, 0xcc, 0x35, 0xe7, 0x09, 0x9f, 0xe1, 0xc8, 0x16, 0x2d, 0x4b, 0xb2, 0x07, 0xee, 0x55, 0x92,
	0x4b, 0x15, 0x2a, 0x9d, 0xcd, 0x19, 0xce, 0xad, 0x50, 0x40, 0x68, 0x64, 0x10, 0x23, 0x40, 0x2a,
	0x9c, 0x0a, 0xcd, 0x95, 0xb7, 0x61, 0x05, 0x08, 0x0d, 0x0c, 0x42, 0x9e, 0x40, 0x4b, 0xaa, 0x28,
	0x57, 0xa1, 0xce, 0xbc, 0x3a, 0xb2, 0x4d, 0xac, 0xc7, 0x19, 0x79, 0x04, 0x75, 0x25, 0x54, 0x34,
	0xf7, 0x1a, 0x88, 0xdb, 0xc2, 0x2c, 0xc3, 0xb1, 0x5f, 0x7a, 0x4d, 0xab, 0x2f, 0x4a, 0xb2, 0x0d,
	0x0d, 0x3e, 0x17, 0x22, 0x93, 0x5e, 0x0b, 0x89, 0xa2, 0x22, 0x3d, 0xd8, 0x62, 0x37, 0x6c, 0x1a,
	0xa6, 0x2c, 0x0d, 0xb5, 0x64, 0xb1, 0xe7, 0x20, 0xed, 0x1a, 0xf0, 0x8c, 0xa5, 0x63, 0xc9, 0x62,
	0xa3, 0x59, 0x88, 0xfc, 0xfa, 0x56, 0x03, 0x56, 0x63, 0xc0, 0x52, 0xf3, 0x12, 0x3a, 0x2b, 0xcd,
	0x22, 0xe2, 0x8a, 0xc5, 0x9e, 0x8b, 0xaa, 0xad, 0x42, 0xf5, 0x05, 0xc1, 0xde, 0xef, 0x2a, 0x38,
	0x17, 0x26, 0x07, 0x01, 0xbf, 0x12, 0xe6, 0x80, 0x18, 0x8a, 0xf2, 0x22, 0x1d, 0xda, 0xc4, 0x3a,
	0x88, 0xc9, 0x2e, 0xb4, 0xe2, 0x48, 0x45, 0x93, 0x48, 0x32, 0x34, 0xd6, 0xa1, 0xab, 0x9a, 0x10,
	0xd8, 0xd0, 0x92, 0xe5, 0x68, 0xa9, 0x43, 0xf1, 0x3b, 0x39, 0x02, 0x57, 0xea, 0x49, 0x9a, 0xa8,
	0xd0, 0x24, 0x08, 0xcd, 0x34, 0xb7, 0x67, 0xe3, 0xd5, 0x2f, 0xe3, 0xd5, 0x1f, 0x95, 0xf1, 0xa2,
	0x60, 0xe5, 0x06, 0x20, 0xef, 0x00, 0xac, 0xd1, 0xd8, 0x5b, 0x5f, 0xdb, 0xeb, 0xa0, 0x1a, 0x5b,
	0x8f, 0xcc, 0x2d, 0xf3, 0x44, 0x7e, 0xb7, 0xbd, 0x8d, 0xf5, 0x73, 0xad, 0x1c, 0x9b, 0x0f, 0xa0,
	0x21, 0x55, 0xa4, 0xb4, 0xbd, 0xae, 0xf6, 0xe1, 0x4e, 0x99, 0x36, 0x9f, 0xeb, 0x14, 0x6d, 0xba,
	0x44, 0x9a, 0x16, 0xb2, 0xde, 0xaf, 0x2a, 0xb4, 0xfc, 0x1b, 0x36, 0x5d, 0xe7, 0xde, 0x5b, 0x68,
	0x61, 0xde, 0x4d, 0x90, 0xab, 0x6b, 0x83, 0x8c, 0x6f, 0xc3, 0x3c, 0xab, 0xfe, 0x6a, 0x9f, 0x1a,
	0xee, 0xb3, 0x7d, 0x77, 0x1f, 0xa3, 0xbe, 0xbf, 0x0e, 0x79, 0x01, 0x9b, 0xe8, 0x84, 0xce, 0xc2,
	0xa9, 0x90, 0x65, 0x84, 0xdd, 0x02, 0x1b, 0x08, 0xa9, 0xc8, 0x33, 0x00, 0xcc, 0xa6, 0x15, 0xd8,
	0x14, 0x3b, 0x88, 0x20, 0xfd, 0x14, 0x9c, 0x6c, 0x1e, 0xf1, 0x30, 0x17, 0x0b, 0x59, 0x64, 0xb9,
	0x65, 0x00, 0x2a, 0x16, 0xd2, 0x90, 0x78, 0x0a, 0xb5, 0xcc, 0x18, 0x3a, 0x54, 0xa7, 0x78, 0xac,
	0xd1, 0x32, 0x63, 0xfb, 0x3f, 0xa1, 0xf3, 0x8f, 0x4b, 0xa4, 0x0b, 0x9b, 0x17, 0x63, 0x9f, 0x7e,
	0x0d, 0x2f, 0x83, 0x53, 0x7f, 0x38, 0xea, 0x3e, 0xb8, 0x83, 0x8c, 0x3f, 0x9c, 0x05, 0xa3, 0x6e,
	0x85, 0x74, 0xc0, 0x2d, 0x90, 0xd1, 0x31, 0x1d, 0x75, 0xab, 0xa4, 0x0d, 0x60, 0x81, 0x93, 0xf3,
	0xa1, 0xdf, 0xad, 0xdd, 0x0a, 0x7c, 0x4a, 0xcf, 0x69, 0x77, 0x83, 0x3c, 0x84, 0x8e, 0x05, 0x06,
	0xc7, 0xc3, 0x81, 0x7f, 0x1a, 0x0c, 0x3f, 0x76, 0xeb, 0xfb, 0xef, 0xa1, 0x7d, 0xdf, 0x13, 0xb2,
	0x05, 0xce, 0xf0, 0xfc, 0xc4, 0x0f, 0x83, 0x61, 0x60, 0x26, 0xb7, 0x01, 0xb0, 0xb4, 0x63, 0x2a,
	0x2b, 0x1a, 0xa7, 0x54, 0x27, 0xf6, 0xff, 0xef, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec,
	0xec, 0x6b, 0xc7, 0x15, 0x05, 0x00, 0x00,
}
